version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: yamato_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: local
    volumes:
      - ./app:/var/www/html         # bind your Yamato-Laravel-API here
      - composer-cache:/tmp/composer-cache
    networks: [yamato]

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: yamato_nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    networks: [yamato]

  postgres:
    image: postgres:16
    container_name: yamato_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: yamato
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yamato || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [yamato]

  redis:
    image: redis:7-alpine
    container_name: yamato_redis
    networks: [yamato]


  mailpit:
    image: axllent/mailpit:latest
    container_name: yamato_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks: [yamato]

volumes:
  pgdata:
  composer-cache:

networks:
  yamato:
    driver: bridge
